/**
 * Código QR institucional de Sirius para los documentos PDF, empotrado en base64.
 *
 * Va incrustado por la misma razón que el logo: el generador corre en el
 * servidor y leerlo de `public/` o de una CDN haría que el documento saliera
 * sin él según dónde esté desplegada la aplicación o si la red falla.
 *
 * Fuente: sirius_qr (Cloudinary), 410x410 px.
 */

/** PNG cuadrado — alto y ancho son iguales al dibujarlo. */
export const QR_SIRIUS_BASE64 =
  "data:image/png;base64," +
    "iVBORw0KGgoAAAANSUhEUgAAAZoAAAGaCAIAAAC5ZBI0AAAH4UlEQVR4nO3dO7LcNhBAUculVEv1arxULWCc2gnLNh7UwOU5ud5w" +
    "PrqFoJv89vl8fgO43+/TFwDwNeQMiJAzIELOgAg5AyLkDIiQMyBCzoAIOQMi5AyIkDMgQs6ACDkDIuQMiJAzIELOgAg5AyLkDIiQ" +
    "MyBCzoAIOQMi5AyIkDMgQs6ACDkDIuQMiJAzIELOgAg5AyLkDIiQMyBCzoAIOQMi5AyIkDMgQs6ACDkDIuQMiJAzIELOgAg5AyLk" +
    "DIiQMyBCzoAIOQMi5AyIkDMgQs6ACDkDIuQMiJAzIELOgAg5AyLkDIiQMyBCzoAIOQMi5AyIkDMg4vv0BfwfP/74OX0JX+znnz+m" +
    "L+GXWvkGnz+r57889W9vdONv0ukMiJAzIELOgAg5AyLkDIiQMyBCzoAIOQMi5AyIuHIr4NmZ08wrU+Nvmzh/fr8rs/tTzryq3u/K" +
    "6QyIkDMgQs6ACDkDIuQMiJAzIELOgAg5AyLkDIgIbgU82zcJfebk98pVnXlH/2c3Trq/7Te5j9MZECFnQIScARFyBkTIGRAhZ0CE" +
    "nAERcgZEyBkQ8bqtgLc5c+J8ZWdg5S8/u3GjgL9zOgMi5AyIkDMgQs6ACDkDIuQMiJAzIELOgAg5AyJsBVxg3333p+bgzf2zg9MZ" +
    "ECFnQIScARFyBkTIGRAhZ0CEnAERcgZEyBkQ8bqtgJWZ8jO97R2tbEGc+VmdeVU3cjoDIuQMiJAzIELOgAg5AyLkDIiQMyBCzoAI" +
    "OQMiglsBvfvB73sawL4nCZx5zfv+7bPeb/JMTmdAhJwBEXIGRMgZECFnQIScARFyBkTIGRAhZ0DElVsB7q3+7618Vvs+56kp+X2v" +
    "6zd5AqczIELOgAg5AyLkDIiQMyBCzoAIOQMi5AyIkDMg4sqtgH33dN9n6pqn7p3fe0crGwVnPmfgzP8pK5zOgAg5AyLkDIiQMyBC" +
    "zoAIOQMi5AyIkDMgQs6AiCu3AlZMzVjvm1Z/duZ0/r6/PPUUgqmNgqn3eyanMyBCzoAIOQMi5AyIkDMgQs6ACDkDIuQMiJAzIOLb" +
    "5/OZvoYv1psLX3HmVa3o7Tk8693Rfx+nMyBCzoAIOQMi5AyIkDMgQs6ACDkDIuQMiJAzIOLKrYDeLPuZ8+grpu6dv8++7+jM172R" +
    "0xkQIWdAhJwBEXIGRMgZECFnQIScARFyBkTIGRBx5VbAmfZNut+4M7Dvqs6cv7fncAKnMyBCzoAIOQMi5AyIkDMgQs6ACDkDIuQM" +
    "iJAzIOL79AX8alOT0GdOfq/ozf3v+7crf/nMrY8zOZ0BEXIGRMgZECFnQIScARFyBkTIGRAhZ0CEnAERV24FrExRT839T91LvjdT" +
    "PvVJ3rjJcOP9/lc4nQERcgZEyBkQIWdAhJwBEXIGRMgZECFnQIScARFXbgXcONs9NZ2/sqtw5gbFvu2LKVPvd+rb38fpDIiQMyBC" +
    "zoAIOQMi5AyIkDMgQs6ACDkDIuQMiLhyK2DFmffO3/c0gH0T51Of5I2z7GfuOZz5Wa1wOgMi5AyIkDMgQs6ACDkDIuQMiJAzIELO" +
    "gAg5AyK+fT6f6Wv4z6bmpN82j77yl/c5c4b+ba97JqczIELOgAg5AyLkDIiQMyBCzoAIOQMi5AyIkDMgwrMC/mHfPexX7JvPXtkZ" +
    "uHGjYJ99n0Zvr2MfpzMgQs6ACDkDIuQMiJAzIELOgAg5AyLkDIiQMyAi+KyAG+9x/uzG+9Cf+S3cuLnBv+d0BkTIGRAhZ0CEnAER" +
    "cgZEyBkQIWdAhJwBEXIGRLzuWQHPpu7LPnVX/t596Kem82/c3Fh53TM5nQERcgZEyBkQIWdAhJwBEXIGRMgZECFnQIScARFXPivg" +
    "bW68Z//UNa/sOUw9g+LG7/dMTmdAhJwBEXIGRMgZECFnQIScARFyBkTIGRAhZ0DElVsBU/eh32dq4nxqSv7MnYGV1933Oa94286A" +
    "0xkQIWdAhJwBEXIGRMgZECFnQIScARFyBkTIGRDxffoCvt6Zk9BTmwxnzv2f+R2t2PeOztwYOZPTGRAhZ0CEnAERcgZEyBkQIWdA" +
    "hJwBEXIGRMgZEBHcCnj2tvuyr7zffZ/V1LMCVkztdZz5FIIzOZ0BEXIGRMgZECFnQIScARFyBkTIGRAhZ0CEnAERr9sKeJt99/uf" +
    "MrXXMXVn/efXtTPwd05nQIScARFyBkTIGRAhZ0CEnAERcgZEyBkQIWdAhK2AuKlZ9hVnXtWzMyfsb/z2VzidARFyBkTIGRAhZ0CE" +
    "nAERcgZEyBkQIWdAhJwBEa/bCuhNQu9z43MGpubg9z1nYOWTPPPpB/s4nQERcgZEyBkQIWdAhJwBEXIGRMgZECFnQIScARHBrYAz" +
    "79q+Yt9c+L7XfTZ1VTfuDOxz49z/M6czIELOgAg5AyLkDIiQMyBCzoAIOQMi5AyIkDMg4tvn85m+BoAv4HQGRMgZECFnQIScARFy" +
    "BkTIGRAhZ0CEnAERcgZEyBkQIWdAhJwBEXIGRMgZECFnQIScARFyBkTIGRAhZ0CEnAERcgZEyBkQIWdAhJwBEXIGRMgZECFnQISc" +
    "ARFyBkTIGRAhZ0CEnAERcgZEyBkQIWdAhJwBEXIGRMgZECFnQIScARFyBkTIGRAhZ0CEnAERcgZEyBkQIWdAhJwBEXIGRMgZECFn" +
    "QIScARFyBkTIGRAhZ0CEnAERcgZEyBkQIWdAxF8sUgwUPxC7OwAAAABJRU5ErkJggg==";
